"""Cluster credentials utilities.

Fetches K3s cluster join credentials from AWS SSM Parameter Store and Secrets Manager.
This is used by the autoscaler to get the master IP and join token needed for
bootstrapping new worker nodes.
"""

import base64
import json
import logging
from typing import Optional

import boto3
from botocore.exceptions import ClientError

from utils.config import get_config

logger = logging.getLogger(__name__)


class ClusterCredentials:
    """K3s cluster credentials for node join operations.

    Attributes:
        master_ip: K3s master node IP address
        join_token: K3s cluster join token
        cluster_url: Full K3s API URL (https://<master-ip>:6443)
    """

    def __init__(self, master_ip: str, join_token: str):
        """Initialize cluster credentials.

        Args:
            master_ip: K3s master node IP address
            join_token: K3s cluster join token
        """
        self.master_ip = master_ip
        self.join_token = join_token
        self.cluster_url = f"https://{master_ip}:6443"

    def __repr__(self) -> str:
        """Return string representation (with token masked)."""
        masked_token = f"{self.join_token[:10]}..." if self.join_token else "None"
        return f"ClusterCredentials(master_ip={self.master_ip}, token={masked_token})"


def get_cluster_credentials(
    ssm_client: Optional[boto3.client] = None,
    secrets_client: Optional[boto3.client] = None,
) -> Optional[ClusterCredentials]:
    """Fetch K3s cluster credentials from AWS services.

    Retrieves the master IP from SSM Parameter Store and join token from
    Secrets Manager. These are populated by Ansible during initial cluster setup.

    Args:
        ssm_client: Optional boto3 SSM client
        secrets_client: Optional boto3 Secrets Manager client

    Returns:
        ClusterCredentials if successful, None if credentials not found

    Raises:
        RuntimeError: If AWS API calls fail
    """
    config = get_config()

    # Initialize clients if not provided
    if ssm_client is None:
        ssm_client = boto3.client("ssm")
    if secrets_client is None:
        secrets_client = boto3.client("secretsmanager")

    try:
        # Fetch master IP from SSM Parameter Store
        parameter_name = f"/k3s/{config.cluster_name}/master-ip"
        logger.info(f"Fetching master IP from SSM: {parameter_name}")

        ssm_response = ssm_client.get_parameter(
            Name=parameter_name,
            WithDecryption=False,  # Not encrypted, just plaintext
        )

        master_ip = ssm_response["Parameter"]["Value"]

        if master_ip == "PENDING":
            logger.warning("Master IP parameter is PENDING - cluster may not be fully setup")
            return None

        logger.info(f"Retrieved master IP: {master_ip}")

        # Fetch join token from Secrets Manager
        secret_name = f"k3s-{config.cluster_name}-join-token"
        logger.info(f"Fetching join token from Secrets Manager: {secret_name}")

        secrets_response = secrets_client.get_secret_value(
            SecretId=secret_name,
        )

        # Parse secret value (can be SecretString or SecretBinary)
        if "SecretString" in secrets_response:
            join_token = secrets_response["SecretString"]
        else:
            # Handle binary secret
            join_token = base64.b64decode(secrets_response["SecretBinary"]).decode("utf-8")

        if join_token == "PENDING":
            logger.warning("Join token secret is PENDING - cluster may not be fully setup")
            return None

        logger.info("Retrieved join token successfully")

        return ClusterCredentials(
            master_ip=master_ip,
            join_token=join_token,
        )

    except ssm_client.exceptions.ParameterNotFound:
        logger.error(f"SSM parameter not found: {parameter_name}")
        return None
    except secrets_client.exceptions.ResourceNotFoundException:
        logger.error(f"Secrets Manager secret not found: {secret_name}")
        return None
    except ClientError as e:
        logger.exception(f"Failed to fetch cluster credentials: {e}")
        raise RuntimeError(f"Failed to fetch cluster credentials: {e}") from e


def generate_user_data_script(credentials: ClusterCredentials) -> str:
    """Generate cloud-init user-data script for K3s worker join.

    This script is passed to EC2 instances via user-data and runs on first boot
    to install k3s-agent and join the cluster.

    Args:
        credentials: Cluster credentials for joining

    Returns:
        User-data script as a string
    """
    script = f"""#!/bin/bash
set -e

# K3s Worker Node Bootstrap Script
# Generated by K3s Autoscaler Lambda

LOG_FILE="/var/log/k3s-worker-bootstrap.log"
echo "Starting K3s worker bootstrap at $(date)" | tee -a "$LOG_FILE"

# Install k3s agent
echo "Installing k3s agent..." | tee -a "$LOG_FILE"
curl -sfL https://get.k3s.io | \\
    K3S_URL={credentials.cluster_url} \\
    K3S_TOKEN={credentials.join_token} \\
    INSTALL_K3S_EXEC="agent --node-name=$(hostname -f)" \\
    sh -

# Wait for k3s-agent to start
echo "Waiting for k3s-agent to start..." | tee -a "$LOG_FILE"
for i in {{1..30}}; do
    if systemctl is-active --quiet k3s-agent; then
        echo "k3s-agent is running" | tee -a "$LOG_FILE"
        break
    fi
    if [ $i -eq 30 ]; then
        echo "Timeout waiting for k3s-agent" | tee -a "$LOG_FILE"
        exit 1
    fi
    sleep 2
done

# Signal completion
echo "Bootstrap completed at $(date)" | tee -a "$LOG_FILE"
"""
    return script
